<?php require('template/header.phtml'); ?>

    <!-- Add a Post -->
    <h2>Create New Post :</h2>


    <!-- show input boxes with values of original so they can easily just modify existing -->
    <form action="add_post.php" method="POST" enctype="multipart/form-data">


        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="floatingTitle" name="title" required>
            <label for="floatingName">Title</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingSalary" name="salary" required>
            <label for="floatingSpecies">Salary</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingLocation" name="location" required>
            <label for="floatingBreed">Location</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingStart" name="start" required>
            <label for="floatingColor">Start Date</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingEnd" name="end" required>
            <label for="floatingColor">End date</label>
        </div>
<!--        <div class="mb-3">-->
<!--            <label for="formFile" class="form-label">Add an Image (Optional)</label>-->
<!--            <p><strong>Photo:<input type="file" name="petphoto" class="form-control" accept=".gif,.jpg,.jpeg,.png"></p>-->
<!--        </div>-->
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingDescription" name="description" placeholder="Description of Pet" required>
            <label for="floatingDescription">Description</label>
        </div>

        <button type="submit" class="btn btn-primary" name="add_post">Save Changes</button>

    </form>

<?php require('template/footer.phtml'); ?>