<?php require('template/header.phtml'); ?>

    <div class="container mt-4">

        <h2 class="mb-4">Placement Opportunities</h2>



        <div class="row">
            <?php
            // Use $view->placements from the controller
            foreach ($view->placements as $placement) { ?>
                <div class="col-md-6 mb-4">
                    <div class="card shadow-sm">
                        <div class="card-body">

                            <h4 class="card-title"><?= $placement->getTitle();
                                ?></h4>
                            <p class="card-text"><?= $placement->getDescription();
                                ?></p>

                            <?php if ($placement->getDeadline()): ?>
                                <div class="w3-panel w3-red">
                                    <p>Deadline: <?php echo $placement->getDeadline(); ?></p>
                                </div>
                            <?php endif; ?>
                            <ul class="list-group list-group-flush mb-3">
                                <li class="list-group-item"><strong>Salary:</strong> £<?= $placement->getSalary();
                                    ?></li>
                                <li class="list-group-item"><strong>Location:</strong> <?= $placement->getLocation();
                                    ?></li>
                                <li class="list-group-item"><strong>Start:</strong> <?= $placement->getStartDate();
                                    ?></li>
                                <li class="list-group-item"><strong>End:</strong> <?= $placement->getEndDate();
                                    ?></li>
                            </ul>


                            <form action="view_details.php" method="POST">
                                <button type="submit" class="btn btn-primary w-100" name ="view" value="<?php echo $placement->getPlacementID()
                                ?>">
                                    View Details
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>

    </div>

<?php require('template/footer.phtml');
?>