<?php require('template/header.phtml'); ?>

    <!-- The Edit pet record page -->
    <h2>Edit Post Details</h2>

    <!-- if error display it -->
<?php if (isset($view->error)): ?>
    <div class="alert alert-danger"><?php echo $view->error; ?></div>
<?php endif; ?>

    <!-- show input boxes with values of original so they can easily just modify existing -->
    <form action="edit_post.php" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="post_id" value="<?php echo htmlspecialchars($view->placement->getPlacementID()); ?>">
        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="title"
                   value="<?php echo htmlspecialchars($view->placement->getTitle()); ?>" required>
            <label for="title">Title</label>
        </div>

        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="salary"
                   value="<?php echo htmlspecialchars($view->placement->getSalary()); ?>" required>
            <label for="salary">Salary (e.g., 20000.00)</label>
        </div>

        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="location"
                   value="<?php echo htmlspecialchars($view->placement->getLocation()); ?>" required>
            <label for="location">Location</label>
        </div>

        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="start"
                   value="<?php echo htmlspecialchars($view->placement->getStartDate()); ?>" required>
            <label for="start">Start Date</label>
        </div>

        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="end"
                   value="<?php echo htmlspecialchars($view->placement->getEndDate()); ?>" required>
            <label for="end">End Date</label>
        </div>

        <!-- <div class="mb-3">-->

        <!-- <label for="formFile" class="form-label">Change Image (Optional)</label>-->

        <!-- <p><strong>Photo:<input type="file" name="petphoto" class="form-control" accept=".gif,.jpg,.jpeg,.png"-->

        <!-- value="--><?php //echo htmlspecialchars($view->post->getPhotoUrl()); ?><!--"></p>-->

        <!-- </div>-->

        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="deadline"
                   value="<?php echo htmlspecialchars($view->placement->getDeadline()); ?>" required>
            <label for="end">Deadline</label>
        </div>

        <div class="form-floating mb-3">
            <textarea class="form-control" name="description" style="height: 100px;">
                <?php echo htmlspecialchars($view->placement->getDescription()); ?>
            </textarea>
            <label for="description">Description</label>
        </div>

        <div class="form-floating mb-3">
            <textarea class="form-control" name="about" style="height: 100px;">
                <?php echo htmlspecialchars($view->placement->getAboutCompany()); ?>
            </textarea>
            <label for="about">About</label>
        </div>

        <div class="form-floating mb-3">
            <textarea class="form-control" name="offer" style="height: 100px;">
                <?php echo htmlspecialchars($view->placement->getWhatWeOffer()); ?>
            </textarea>
            <label for="about">What You offer</label>
        </div>

        <!-- Allow to cancel or confirm edit-->
        <a href="my_posts.php" class="btn btn-secondary">Cancel</a>
        <button type="submit" class="btn btn-primary" name="update_post">Save Changes</button>
    </form>

<?php require('template/footer.phtml'); ?>