<?php require('template/header.phtml');
?>

    <div class="row">
    <div class="col-5">
        <form action="posts.php" method="POST" class="form-inline my-2 my-lg-0">
        </form>
    </div>

<?php if (isset($_SESSION['role']) == "employer"):?>

    </div>

    <div class="col-3">
        <button class="btn btn-outline-success my-4 my-sm-2" type="submit" data-bs-toggle="collapse" data-bs-target="#advancedOptions" aria-expanded="false" aria-controls="advancedOptions" >Advanced Search
        </button>
    </div>



    <?php if (isset($view->success)) : ?>
        <div class="alert alert-success mt-3 text-center">
            <?php echo htmlspecialchars($view->success); ?>
        </div>
    <?php endif; ?>


    <div class="col-4">
        <p>Current script <?php echo $_SERVER["PHP_SELF"]; ?></p>
    </div>

    <div class="col-2">
        <p><?php echo $view->dbMessage; ?></p>
    </div>

    <div class="row row-cols-1 row-cols-md-3 g-4 my-4">
        <?php foreach ($view->placementsDataSet as $placementsData) { ?>
            <div class="col">
                <div class="card border-dark mb-3 h-100">
                    <div class="card-header">
                        <h5><?php echo $placementsData->getTitle(); ?></h5>
                        <div class="w3-panel w3-red">
                            <p>Deadline: <?php echo $placementsData->getDeadline(); ?></p>
                        </div>
                        <form action="my_posts.php" method="POST">
                            <input type="hidden" name="post_id" value="<?php echo $placementsData->getPlacementID(); ?>">
                            <?php if ($placementsData->getStatus() == "inactive"):?>
                            <button type="submit" class="btn btn-primary" name ="activate_status">
                                Activate post
                            </button>
                            <?php endif; ?>
                            <?php if ($placementsData->getStatus() == "active"):?>
                                <button type="submit" class="btn btn-primary" name ="de-activate_status">
                                    De-activate post
                                </button>
                            <?php endif; ?>
                        </form>
                        <form action="display_matches.php" method="POST">
                            <input type="hidden" name="post_id" value="<?php echo $placementsData->getPlacementID(); ?>">
                            <button type="submit" class="btn btn-info" name ="matches">
                                Matches: <?php echo $placementsData->matchCount; ?>
                            </button>
                        </form>
                    </div>
                    <?php //echo 'images/' .  htmlspecialchars($placementsData->getPhotoUrl())?><div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text"><b>salary: £</b> <?php echo $placementsData->getSalary()?></p>
                            <p class="card-text"><b>location:</b> <?php echo $placementsData->getLocation()?></p>
                            <p class="card-text"><b>start date:</b> <?php echo $placementsData->getStartDate()?></p>
                            <p class="card-text"><b>end date:</b> <?php echo $placementsData->getEndDate()?></p>
                        </div>
                        <div class="card-footer">
                            <!-- delete specific card  -->
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal<?php echo $placementsData->getPlacementID(); ?>">
                                Delete Draft
                            </button>
                            <form action="edit_post.php" method="POST">
                                <button type="submit" class="btn btn-warning" name ="id" value="<?php echo $placementsData->getPlacementID() ?>">
                                    Edit
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Conformation Modal to make sure delete is needed  -->
            <div class="modal fade" id="deleteModal<?php echo $placementsData->getPlacementID(); ?>" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                    <form action="my_posts.php" method="POST" class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Delete Placement </h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to delete this placement</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-danger" name="delete_placement" value="<?php echo $placementsData->getPlacementID()?>">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        <?php } ?>
    </div>
<?php endif; ?>


<?php require('template/footer.phtml') ?>