<?php require('template/header.phtml');
?>


<div class="row">
    <div class="col-5">
        <form action="posts.php" method="POST" class="form-inline my-2 my-lg-0">
        </form>
    </div>

<?php if (isset($_SESSION['role']) == "employer"):?>

</div>


<div class="col-3">
    <button class="btn btn-outline-success my-4 my-sm-2" type="submit" data-bs-toggle="collapse" data-bs-target="#advancedOptions" aria-expanded="false" aria-controls="advancedOptions" >Advanced Search
    </button>
</div>



<?php if (isset($view->success)) : ?>
<!-- if success show appropriate message -->
    <div class="alert alert-success mt-3 text-center">
        <?php echo htmlspecialchars($view->success); ?>
    </div>
<?php endif; ?>


<div class="col-4">
    <p>Current script <?php echo $_SERVER["PHP_SELF"]; ?></p>
</div>

<div class="col-2">
    <p><?php echo $view->dbMessage; ?></p>
</div>

    <!-- Display all records as cards -->
<div class="row row-cols-1 row-cols-md-3 g-4 my-4">
    <?php foreach ($view->placementsDataSet as $placementsData) { ?>
        <div class="col">
            <div class="card border-dark mb-3 h-100">
                <div class="card-header">
                        <h5><?php echo $placementsData->getTitle(); ?></h5>
                </div>
<!--                <div class="col-md-4">-->
<!--                        <img src= "--><?php //echo 'images/' .  htmlspecialchars($placementsData->getPhotoUrl())?><!--"-->
<!--                             class="img-fluid rounded-start w-50 h-100 " alt="No Image">-->
<!--                </div>-->

                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text"><b>salary:</b> <?php echo $placementsData->getSalary()?></p>
                        <p class="card-text"><b>location:</b> <?php echo $placementsData->getLocation()?></p>
                        <p class="card-text"><b>start date:</b> <?php echo $placementsData->getStartDate()?></p>
                        <p class="card-text"><b>end date:</b> <?php echo $placementsData->getEndDate()?></p>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </div>

    <?php } ?>
</div>
<?php endif; ?>

<?php require('template/footer.phtml') ?>